import { Platform } from 'react-native';

export const AppTheme = {
  light: {
    bg: '#fafafa',
    bgElevated: '#ffffff',
    surface: '#f2f2f2',
    surfaceStrong: '#f2f2f2',
    surfaceHover: '#e9ebef',
    border: 'rgba(0, 0, 0, 0.1)',
    text: '#111111',
    textMuted: '#5f5f5f',
    primary: '#4caf50',
    primaryHover: '#439a47',
    primarySoft: '#244226',
    primaryStrong: '#1f7a35',
    primaryForeground: '#ffffff',
    accent: '#e9ebef',
    accentWarm: '#ff8a4c',
    accentCool: '#21c7c2',
    secondary: '#f2f2f2',
    secondaryForeground: '#111111',
    muted: '#f2f2f2',
    mutedForeground: '#5f5f5f',
    inputBackground: '#f2f2f2',
    danger: '#d4183d',
    success: '#2e7d32',
  },
  dark: {
    bg: '#111111',
    bgElevated: '#181818',
    surface: '#1f1f1f',
    surfaceStrong: '#1f1f1f',
    surfaceHover: '#1f1f1f',
    border: 'rgba(255, 255, 255, 0.1)',
    text: '#fafafa',
    textMuted: '#b3b3b3',
    primary: '#4caf50',
    primaryHover: '#66bb6a',
    primarySoft: '#a5d6a7',
    primaryStrong: '#8edd91',
    primaryForeground: '#111111',
    accent: '#1f1f1f',
    accentWarm: '#ff9e67',
    accentCool: '#61d9d4',
    secondary: '#1f1f1f',
    secondaryForeground: '#fafafa',
    muted: '#1f1f1f',
    mutedForeground: '#b3b3b3',
    inputBackground: '#1f1f1f',
    danger: '#d4183d',
    success: '#66bb6a',
  },
} as const;

export const Colors = {
  light: {
    text: AppTheme.light.text,
    background: AppTheme.light.bg,
    tint: AppTheme.light.primary,
    icon: AppTheme.light.textMuted,
    tabIconDefault: AppTheme.light.textMuted,
    tabIconSelected: AppTheme.light.primary,
  },
  dark: {
    text: AppTheme.dark.text,
    background: AppTheme.dark.bg,
    tint: AppTheme.dark.primary,
    icon: AppTheme.dark.textMuted,
    tabIconDefault: AppTheme.dark.textMuted,
    tabIconSelected: AppTheme.dark.primary,
  },
} as const;

export const ThemeVariables = {
  light: {
    '--bg': AppTheme.light.bg,
    '--bg-elevated': AppTheme.light.bgElevated,
    '--surface': AppTheme.light.surface,
    '--surface-strong': AppTheme.light.surfaceStrong,
    '--surface-hover': AppTheme.light.surfaceHover,
    '--border': AppTheme.light.border,
    '--text': AppTheme.light.text,
    '--text-muted': AppTheme.light.textMuted,
    '--primary': AppTheme.light.primary,
    '--primary-hover': AppTheme.light.primaryHover,
    '--primary-soft': AppTheme.light.primarySoft,
    '--primary-strong': AppTheme.light.primaryStrong,
    '--primary-foreground': AppTheme.light.primaryForeground,
    '--accent': AppTheme.light.accent,
    '--accent-warm': AppTheme.light.accentWarm,
    '--accent-cool': AppTheme.light.accentCool,
    '--secondary': AppTheme.light.secondary,
    '--secondary-foreground': AppTheme.light.secondaryForeground,
    '--muted': AppTheme.light.muted,
    '--muted-foreground': AppTheme.light.mutedForeground,
    '--input-background': AppTheme.light.inputBackground,
    '--danger': AppTheme.light.danger,
    '--success': AppTheme.light.success,
  },
  dark: {
    '--bg': AppTheme.dark.bg,
    '--bg-elevated': AppTheme.dark.bgElevated,
    '--surface': AppTheme.dark.surface,
    '--surface-strong': AppTheme.dark.surfaceStrong,
    '--surface-hover': AppTheme.dark.surfaceHover,
    '--border': AppTheme.dark.border,
    '--text': AppTheme.dark.text,
    '--text-muted': AppTheme.dark.textMuted,
    '--primary': AppTheme.dark.primary,
    '--primary-hover': AppTheme.dark.primaryHover,
    '--primary-soft': AppTheme.dark.primarySoft,
    '--primary-strong': AppTheme.dark.primaryStrong,
    '--primary-foreground': AppTheme.dark.primaryForeground,
    '--accent': AppTheme.dark.accent,
    '--accent-warm': AppTheme.dark.accentWarm,
    '--accent-cool': AppTheme.dark.accentCool,
    '--secondary': AppTheme.dark.secondary,
    '--secondary-foreground': AppTheme.dark.secondaryForeground,
    '--muted': AppTheme.dark.muted,
    '--muted-foreground': AppTheme.dark.mutedForeground,
    '--input-background': AppTheme.dark.inputBackground,
    '--danger': AppTheme.dark.danger,
    '--success': AppTheme.dark.success,
  },
} as const;

export const Fonts = Platform.select({
  ios: {
    sans: 'Inter_400Regular',
    serif: 'Times New Roman',
    rounded: 'Sora_700Bold',
    mono: 'ui-monospace',
  },
  default: {
    sans: 'Inter_400Regular',
    serif: 'serif',
    rounded: 'Sora_700Bold',
    mono: 'monospace',
  },
  web: {
    sans: 'var(--font-sans)',
    serif: "Georgia, 'Times New Roman', serif",
    rounded: 'var(--font-display)',
    mono: 'var(--font-mono)',
  },
});
